app = "eternal-garden-c795f9b8-d39a-4f1b-a50d-210546aaebd9"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
